api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Enable access logs
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  bufferingSize: 100

# Enable application logs
log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

# Enable Prometheus metrics
metrics:
  prometheus:
    entryPoint: metrics
    addServicesLabels: true
    addEntryPointsLabels: true